apiVersion: v1
appVersion: 0.10.0
description: A dynamic Web Map tile server
name: titiler
version: 1.1.0
icon: https://raw.githubusercontent.com/developmentseed/titiler/master/docs/logos/TiTiler_logo_small.png
maintainers:
  - name: emmanuelmathot  # Emmanuel Mathot
    url: https://github.com/emmanuelmathot
