apiVersion: v1
appVersion: 2.0.0a2
description: A dynamic Web Map tile server
name: titiler
version: 2.0.1
icon: https://raw.githubusercontent.com/developmentseed/titiler/main/docs/logos/TiTiler_logo_small.png
maintainers:
  - name: emmanuelmathot  # Emmanuel Mathot
    url: https://github.com/emmanuelmathot
  - name: ciaransweet     # Ciaran Sweet
    url: https://github.com/ciaransweet
