apiVersion: v1
appVersion: 0.18.5
description: A dynamic Web Map tile server
name: titiler
version: 1.1.2
icon: https://raw.githubusercontent.com/developmentseed/titiler/main/docs/logos/TiTiler_logo_small.png
maintainers:
  - name: emmanuelmathot  # Emmanuel Mathot
    url: https://github.com/emmanuelmathot
