apiVersion: v1
appVersion: 1.0.1
description: A dynamic Web Map tile server
name: titiler
version: 1.3.1
icon: https://raw.githubusercontent.com/developmentseed/titiler/main/docs/logos/TiTiler_logo_small.png
maintainers:
  - name: emmanuelmathot  # Emmanuel Mathot
    url: https://github.com/emmanuelmathot
