repos:
    -   
        repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
            - id: isort
              language_version: python3.7
    -
        repo: https://github.com/psf/black
        rev: stable
        hooks:
            - id: black
              args: ['--safe']
              language_version: python3.7
    -
        repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.4.0
        hooks:
            - id: flake8
              language_version: python3.7
              args: [
                  # E501 let black handle all line length decisions
                  # W503 black conflicts with "line break before operator" rule
                  # E203 black conflicts with "whitespace before ':'" rule
                  '--ignore=E501,W503,E203']
    -
        repo: https://github.com/chewse/pre-commit-mirrors-pydocstyle
        # 2.1.1
        rev: 22d3ccf6cf91ffce3b16caa946c155778f0cb20f
        hooks:
            - id: pydocstyle
              language_version: python3.7
              args: [
                 # Check for docstring presence only
                 '--select=D1',
                 # Don't require docstrings for tests
                 '--match=(?!test).*\.py']
    -
        repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.770
        hooks:
            -   id: mypy
                language_version: python3.7
                args: [--no-strict-optional, --ignore-missing-imports]