[project]
name = "titiler-cdk"
version = "0.0.0"

dependencies = [
    # aws cdk
    "aws-cdk-lib==2.201.0",
    "constructs>=10.0.0",
    # pydantic settings
    "pydantic~=2.0",
    "pydantic-settings~=2.0",
]
