[project]
name = "titiler-cdk"
version = "0.0.0"

dependencies = [
    # aws cdk
    "aws-cdk-lib~=2.232.2",
    "constructs>=10.4.2",
    # pydantic settings
    "pydantic~=2.0",
    "pydantic-settings~=2.0",
]
