{{- if .Values.titiler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titiler.fullname" . }}
  labels:
    {{- include "titiler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.titiler.replicaCount }}
  selector:
    matchLabels:
      {{- include "titiler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "titiler.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.titiler.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.titiler.image.repository }}:{{ .Values.titiler.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.titiler.image.pullPolicy }}
          command: [ {{ .Values.titiler.image.command }} ]
          args: [ {{- range $arg := .Values.titiler.image.args }}
            {{- $arg | quote }},
            {{- end }}
          ]
          securityContext:
            {{- toYaml .Values.titiler.securityContext | nindent 12 }}
          env:
          {{- range $key, $val := .Values.titiler.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.titiler.netrc }}
            - name: NETRC
              value: /config/netrc
            - name: CURLOPT_NETRC
              value: CURL_NETRC_OPTIONAL
            - name: CURLOPT_NETRC_FILE
              value: /config/netrc
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.titiler.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.titiler.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
          {{- range .Values.titiler.extraHostPathMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- if .mountPropagation }}
              mountPropagation: {{ .mountPropagation }}
            {{- end }}
          {{- end }}
      terminationGracePeriodSeconds: {{ .Values.titiler.env.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          configMap:
            name: {{ include "titiler.fullname" . }}-configmap
      {{- range .Values.titiler.extraHostPathMounts }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
      {{- end }}
      {{- with .Values.titiler.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
      - name: {{ .name }}
        {{- end }}
      {{- end }}
      {{- with .Values.titiler.serviceAccountName }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
      {{- with .Values.titiler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.titiler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.titiler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end}}
---
{{- if .Values.titiler_xarray.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "titiler_xarray.fullname" . }}
  labels:
    {{- include "titiler_xarray.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.titiler_xarray.replicaCount }}
  selector:
    matchLabels:
      {{- include "titiler_xarray.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "titiler_xarray.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.titiler_xarray.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.titiler_xarray.image.repository }}:{{ .Values.titiler_xarray.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.titiler_xarray.image.pullPolicy }}
          command: [ {{ .Values.titiler_xarray.image.command }} ]
          args: [ {{- range $arg := .Values.titiler_xarray.image.args }}
            {{- $arg | quote }},
            {{- end }}
          ]
          securityContext:
            {{- toYaml .Values.titiler_xarray.securityContext | nindent 12 }}
          env:
          {{- range $key, $val := .Values.titiler_xarray.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- if .Values.titiler_xarray.netrc }}
            - name: NETRC
              value: /config/netrc
            - name: CURLOPT_NETRC
              value: CURL_NETRC_OPTIONAL
            - name: CURLOPT_NETRC_FILE
              value: /config/netrc
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.titiler_xarray.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.titiler_xarray.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /config
              name: config
              readOnly: true
          {{- range .Values.titiler_xarray.extraHostPathMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- if .mountPropagation }}
              mountPropagation: {{ .mountPropagation }}
            {{- end }}
          {{- end }}
      terminationGracePeriodSeconds: {{ .Values.titiler_xarray.env.terminationGracePeriodSeconds }}
      volumes:
        - name: config
          configMap:
            name: {{ include "titiler_xarray.fullname" . }}-configmap
      {{- range .Values.titiler_xarray.extraHostPathMounts }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
            type: Directory
      {{- end }}
      {{- with .Values.titiler_xarray.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
      - name: {{ .name }}
        {{- end }}
      {{- end }}
      {{- with .Values.titiler_xarray.serviceAccountName }}
      serviceAccountName: {{ . | quote }}
      {{- end }}
      {{- with .Values.titiler_xarray.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.titiler_xarray.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.titiler_xarray.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end}}
