{{- if .Values.titiler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "titiler.fullname" . }}
  labels:
    {{- include "titiler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.titiler.service.type }}
  ports:
    - port: {{ .Values.titiler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "titiler.selectorLabels" . | nindent 4 }}
{{- end }}
---
{{- if .Values.titiler_xarray.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "titiler_xarray.fullname" . }}
  labels:
    {{- include "titiler_xarray.labels" . | nindent 4 }}
spec:
  type: {{ .Values.titiler_xarray.service.type }}
  ports:
    - port: {{ .Values.titiler_xarray.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "titiler_xarray.selectorLabels" . | nindent 4 }}
{{- end }}
