name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Only rebuild website when docs have changed
      - 'README.md'
      - 'CHANGES.md'
      - 'CONTRIBUTING.md'
      - 'deployment/**'
      - 'docs/**'
      - '.github/workflows/deploy_mkdocs.yml'

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install src/titiler/core src/titiler/extensions["cogeo,stac"] src/titiler/mosaic src/titiler/application
          python -m pip install nbconvert==6.5.3 mkdocs mkdocs-material mkdocs-jupyter pygments pdocs

      - name: update API docs
        run: |
          pdocs as_markdown \
            --output_dir docs/src/api \
            --exclude_source \
            --overwrite \
            titiler.core.dependencies \
            titiler.core.factory \
            titiler.core.routing \
            titiler.core.errors \
            titiler.core.resources.enums \
            titiler.core.middleware

          pdocs as_markdown \
            --output_dir docs/src/api \
            --exclude_source \
            --overwrite \
            titiler.extensions.cogeo \
            titiler.extensions.viewer \
            titiler.extensions.stac

          pdocs as_markdown \
            --output_dir docs/src/api \
            --exclude_source \
            --overwrite \
            titiler.mosaic.factory \
            titiler.mosaic.resources.enums \
            titiler.mosaic.errors

      - name: Deploy docs
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml
